(function(){"use strict";const b=[15,30,45,60];let a=!1,s=null,l=[],c;if(window.__safetyAI_loaded)throw new Error("Safety AI content script already loaded");window.__safetyAI_loaded=!0;function w(){if(document.getElementById("safeai-timer"))return;const e=document.createElement("div");e.id="safeai-timer",Object.assign(e.style,{position:"fixed",top:"8px",right:"8px",width:"168px",zIndex:"2147483645",background:"#1F3A2E",border:"1px solid #B89968",padding:"10px 12px 8px",borderRadius:"8px",cursor:"grab",userSelect:"none",boxShadow:"0 2px 12px rgba(31,58,46,0.3)"}),e.innerHTML=`
    <div id="safeai-timer-header" style="display:flex;align-items:center;justify-content:space-between;margin-bottom:6px;">
      <div style="font-family:'JetBrains Mono',monospace;font-size:8px;letter-spacing:0.22em;text-transform:uppercase;color:#B89968;">Screen Time</div>
      <div style="font-family:'JetBrains Mono',monospace;font-size:7px;letter-spacing:0.14em;text-transform:uppercase;color:rgba(245,240,230,0.5);">&#128737; Safe</div>
    </div>
    <div id="safeai-timer-display" style="font-family:'JetBrains Mono',monospace;font-size:20px;font-weight:700;color:#F5F0E6;line-height:1.2;">0 min</div>
    <div style="margin-top:7px;height:3px;background:rgba(255,255,255,0.15);overflow:hidden;border-radius:2px;">
      <div id="safeai-timer-bar" style="height:3px;background:#B89968;width:0%;transition:width 0.8s;border-radius:2px;"></div>
    </div>
    <div style="font-family:'JetBrains Mono',monospace;font-size:7px;color:rgba(245,240,230,0.35);letter-spacing:0.08em;margin-top:6px;line-height:1.5;text-align:center;">Don't share personal info<br>Verify answers &middot; Ask an adult</div>`,document.body.appendChild(e),h(e)}function h(e){let t=!1,n=0,d=0;e.addEventListener("mousedown",i=>{t=!0,n=i.clientX-e.getBoundingClientRect().left,d=i.clientY-e.getBoundingClientRect().top,e.style.cursor="grabbing",i.preventDefault()}),document.addEventListener("mousemove",i=>{if(!t)return;let o=i.clientX-n,r=i.clientY-d;o=Math.max(0,Math.min(o,window.innerWidth-e.offsetWidth)),r=Math.max(0,Math.min(r,window.innerHeight-e.offsetHeight)),e.style.left=o+"px",e.style.top=r+"px",e.style.right="auto"}),document.addEventListener("mouseup",()=>{t&&(t=!1,e.style.cursor="grab")})}function v(){var e;(e=document.getElementById("safeai-timer"))==null||e.remove()}function u(e){const t=document.getElementById("safeai-timer-display");t&&(t.textContent=`${e} min`);const n=document.getElementById("safeai-timer-bar");n&&(n.style.width=`${Math.min(e/60*100,100)}%`)}function E(e){var n;(n=document.getElementById("safeai-time-warn"))==null||n.remove();const t=document.createElement("div");t.id="safeai-time-warn",Object.assign(t.style,{position:"fixed",top:"50%",left:"50%",transform:"translate(-50%,-50%)",zIndex:"2147483646",background:"#F5F0E6",border:"2px solid #1F3A2E",padding:"32px 36px",maxWidth:"380px",width:"90vw",textAlign:"center",boxShadow:"0 20px 60px rgba(31,58,46,0.25)",borderRadius:"12px"}),t.innerHTML=`
    <div style="font-size:36px;margin-bottom:12px;">&#9201;</div>
    <div style="font-family:'JetBrains Mono',monospace;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:#B89968;margin-bottom:8px;">Screen Time Check</div>
    <div style="font-family:system-ui,sans-serif;font-size:22px;font-weight:300;color:#1F3A2E;margin-bottom:12px;">You've been online for <strong>${e} minutes</strong></div>
    <div style="font-family:system-ui,sans-serif;font-size:14px;color:#3A4A42;line-height:1.6;margin-bottom:20px;">Time for a short break! Stand up, stretch, or grab a drink of water before continuing.</div>
    <button id="safeai-time-ok" style="background:#1F3A2E;color:#F5F0E6;border:none;padding:12px 28px;font-family:'JetBrains Mono',monospace;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;cursor:pointer;font-weight:600;border-radius:8px;">Got it, thanks</button>`,document.body.appendChild(t),document.getElementById("safeai-time-ok").addEventListener("click",()=>t.remove()),setTimeout(()=>t.parentNode&&t.remove(),3e4)}function y(){if(document.getElementById("safeai-limit-block"))return;const e=document.createElement("div");e.id="safeai-limit-block",Object.assign(e.style,{position:"fixed",inset:"0",zIndex:"2147483647",background:"#1F3A2E",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}),e.innerHTML=`
    <div style="text-align:center;max-width:420px;padding:40px;">
      <div style="font-size:56px;margin-bottom:20px;">&#9200;</div>
      <div style="font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.28em;text-transform:uppercase;color:#B89968;margin-bottom:16px;">Time Limit Reached</div>
      <div style="font-family:system-ui,sans-serif;font-size:28px;font-weight:300;color:#F5F0E6;margin-bottom:16px;line-height:1.3;">Your screen time is up for today.</div>
      <div style="font-family:system-ui,sans-serif;font-size:15px;color:rgba(245,240,230,0.7);line-height:1.7;margin-bottom:32px;">Ask a trusted adult if you need more time. Come back tomorrow!</div>
      <div style="width:60px;height:1px;background:#B89968;margin:0 auto;"></div>
    </div>`,document.body.appendChild(e),document.body.style.overflow="hidden"}function m(e){l=e,s&&s.disconnect(),e.length!==0&&(g(),s=new MutationObserver(()=>{clearTimeout(c),c=window.setTimeout(g,100)}),s.observe(document.body,{childList:!0,subtree:!0,characterData:!0}))}function f(){s&&(s.disconnect(),s=null),clearTimeout(c)}function g(){var n;if(!a||l.length===0||document.getElementById("safeai-kw-block"))return;const e=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let t;for(;t=e.nextNode();){const d=t.parentElement;if(!d||d.closest("#safeai-timer,#safeai-limit-block,#safeai-kw-block,#safeai-time-warn,input,textarea"))continue;const i=((n=t.textContent)==null?void 0:n.toLowerCase())??"";for(const o of l)if(i.includes(o.toLowerCase())){k(o);return}}}function k(e){if(document.getElementById("safeai-kw-block"))return;const t=document.createElement("div");t.id="safeai-kw-block",Object.assign(t.style,{position:"fixed",inset:"0",zIndex:"2147483647",background:"#1F3A2E",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}),t.innerHTML=`
    <div style="text-align:center;max-width:480px;padding:40px;">
      <div style="font-size:56px;margin-bottom:20px;">&#128683;</div>
      <div style="font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.28em;text-transform:uppercase;color:#B89968;margin-bottom:16px;">Flagged Content Detected</div>
      <div style="font-family:system-ui,sans-serif;font-size:26px;font-weight:300;color:#F5F0E6;margin-bottom:14px;line-height:1.3;">Hold on — don't keep reading just yet.</div>
      <div style="font-family:system-ui,sans-serif;font-size:14px;color:rgba(245,240,230,0.7);line-height:1.8;margin-bottom:10px;">The AI's response contains a flagged topic (<em style="color:#B89968;">"${B(e)}"</em>). Please ask a trusted adult to check whether this content is safe and appropriate before you continue.</div>
      <div style="width:60px;height:1px;background:#B89968;margin:20px auto 28px;"></div>
      <div id="safeai-kw-unlock-area">
        <button id="safeai-kw-unlock-btn" style="background:transparent;border:1px solid rgba(184,153,104,0.5);color:#B89968;padding:10px 24px;font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.18em;text-transform:uppercase;cursor:pointer;border-radius:8px;">Parent Unlock</button>
      </div>
    </div>`,document.body.appendChild(t),document.body.style.overflow="hidden",document.getElementById("safeai-kw-unlock-btn").addEventListener("click",()=>{const n=document.getElementById("safeai-kw-unlock-area");n.innerHTML=`
      <input id="safeai-kw-pwd" type="password" placeholder="Parent password" style="background:#EFE9DC;border:1px solid #B89968;color:#1F3A2E;padding:10px 16px;font-family:'JetBrains Mono',monospace;font-size:13px;text-align:center;width:220px;outline:none;margin:0 auto 10px;display:block;border-radius:8px;">
      <div id="safeai-kw-err" style="font-family:'JetBrains Mono',monospace;font-size:9px;color:#B89968;letter-spacing:0.12em;margin-bottom:10px;display:none;">Wrong password.</div>
      <button id="safeai-kw-confirm" style="background:#B89968;border:none;color:#1F3A2E;padding:10px 24px;font-family:'JetBrains Mono',monospace;font-size:10px;letter-spacing:0.18em;text-transform:uppercase;cursor:pointer;font-weight:700;border-radius:8px;">Confirm</button>`;const d=document.getElementById("safeai-kw-confirm"),i=document.getElementById("safeai-kw-pwd"),o=()=>{chrome.runtime.sendMessage({type:"VERIFY_PASSWORD",password:i.value},r=>{r!=null&&r.valid?(t.remove(),document.body.style.overflow="",f(),setTimeout(()=>{a&&m(l)},1e4)):(document.getElementById("safeai-kw-err").style.display="block",i.value="")})};d.addEventListener("click",o),i.addEventListener("keydown",r=>{r.key==="Enter"&&o()})})}function B(e){const t=document.createElement("div");return t.textContent=e,t.innerHTML}function p(e){a=!0,w(),m(e),chrome.runtime.sendMessage({type:"GET_SCREEN_TIME"},t=>{(t==null?void 0:t.minutes)!=null&&u(t.minutes)})}function x(){var e,t,n;a=!1,v(),f(),(e=document.getElementById("safeai-kw-block"))==null||e.remove(),(t=document.getElementById("safeai-time-warn"))==null||t.remove(),(n=document.getElementById("safeai-limit-block"))==null||n.remove(),document.body.style.overflow=""}chrome.runtime.onMessage.addListener(e=>{e.type==="SCREEN_TIME_UPDATE"&&(u(e.minutes),b.includes(e.minutes)&&E(e.minutes)),e.type==="TIME_LIMIT_EXCEEDED"&&y(),e.type==="SAFE_MODE_STATUS"&&(e.enabled?chrome.runtime.sendMessage({type:"GET_SETTINGS"},t=>{t&&p(t.keywords||[])}):x())}),chrome.runtime.sendMessage({type:"GET_SETTINGS"},e=>{chrome.runtime.lastError||!e||e.safeMode&&(p(e.keywords||[]),chrome.runtime.sendMessage({type:"GET_SCREEN_TIME"},t=>{t!=null&&t.timeLimitExceeded&&y()}))}),chrome.storage.onChanged.addListener(e=>{if(!e.settings)return;const t=e.settings.newValue;t&&(t.safeMode&&!a?p(t.keywords||[]):!t.safeMode&&a?x():a&&t.keywords&&(f(),m(t.keywords)))})})();
